version: "3.2"
services:

  database:
    image: 'postgres:latest'
    container_name: 'movies_marker_db'

    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
  
    volumes:
      - ./database_data:/var/lib/postgresql/data
      
  # app:
  #   container_name: ${DOCKER_APP_NAME}
  #   build: ./service
   
  #   environment:
  #     DB_HOST: ${DATABASE_NAME}
  #     DB_PORT: ${POSTGRES_PORT}
  #     APP_PORT: ${APP_PORT}
  #   ports:
  #     - ${APP_PORT}:8000
  #   depends_on:
  #     - database