name: project

on: [push]

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


jobs:
  build:

    runs-on: ubuntu-latest
    environment: backend
    
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${{secrets.POSTGRES_PORT}}:${{secrets.POSTGRES_PORT}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest --verbosity=2
