name: project

on: [push]

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

jobs:
  build:

    runs-on: windows-latest
    environment: backend
    
    steps:
      - name: Start PostgreSQL on Windows
        run: |
          $pgService = Get-Service -Name postgresql*
          Set-Service -InputObject $pgService -Status running -StartupType automatic
          Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
      - name: Create user on Windows
        run: |
          & $env:PGBIN\psql --command="CREATE USER $Env:DATABASE_USERNAME PASSWORD $Env:DATABASE_PASSWORD" --command="\du"
      - name: Create $Env:DATABASE_NAME database
        run: |
          & $env:PGBIN\createdb --owner=$Env:DATABASE_USERNAME $Env:DATABASE_NAME
          $env:PGPASSWORD = $Env:DATABASE_PASSWORD
          & $env:PGBIN\psql --username=$Env:DATABASE_USERNAME --host=localhost --list $Env:DATABASE_NAME
          & $env:PGBIN\createdb --owner=$Env:DATABASE_USERNAME pytest1
          $env:PGPASSWORD = $Env:DATABASE_PASSWORD
          & $env:PGBIN\psql --username=$Env:DATABASE_USERNAME --host=localhost --list pytest1
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest --verbosity=2
