name: project

on: [push]

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


jobs:
  build:

    runs-on: ubuntu-latest
    environment: backend
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r ./service/requirements.txt
      - run: cp .env-example .env
      - run: docker-compose up -d database
      - name: Test with pytest
        run: |
          pytest --verbosity=2
