name: project

on: [push]

jobs:
  build:

    runs-on: windows-latest
    environment: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest --verbosity=2