name: project

on: [push]

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


jobs:
  build:

    runs-on: ubuntu-latest
    environment: backend
    
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Poetry
        run: |
          pip install poetry
          poetry install
      - name: Export
        run: |
          echo APP_PORT=${{ env.APP_PORT }} >> $GITHUB_ENV
          echo POSTGRES_DB=${{ env.DATABASE_NAME }} >> $GITHUB_ENV
          echo POSTGRES_HOST=${{ env.POSTGRES_HOST }} >> $GITHUB_ENV
          echo POSTGRES_USER=${{ env.DATABASE_USERNAME }} >> $GITHUB_ENV
          echo POSTGRES_PORT=${{ env.POSTGRES_PORT }} >> $GITHUB_ENV
          echo POSTGRES_PASSWORD=${{ env.DATABASE_PASSWORD }} >> $GITHUB_ENV
          echo DATABASE_PORT=${{ env.DATABASE_PORT }} >> $GITHUB_ENV
      # - run: cp .env-example .env
      - run: docker-compose up -d database
      - name: Test with pytest
        run: |
          poetry run pytest tests --verbosity=2
