name: project

on: [push]

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


jobs:
  build:

    runs-on: ubuntu-latest
    environment: backend
    
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Poetry
        run: |
          pip install poetry
          poetry install
      - run: cp .env-example .env
      - run: >
          docker-compose up -e APP_PORT
          POSTGRES_DB=DATABASE_NAME
          POSTGRES_HOST
          POSTGRES_USER=DATABASE_USERNAME
          POSTGRES_PORT
          POSTGRES_PASSWORD=DATABASE_PASSWORD
          DATABASE_PORT -d database
      - name: Test with pytest
        run: |
          poetry run pytest tests --verbosity=2
